project:
  type: website
  output-dir: docs

website:
  navbar:
    title: Arod's Bridge
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - posts.qmd # add your posts.qmd file to your navbar!

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

